services:
  hibiscus-server:
    container_name: hibiscus-server
    restart: unless-stopped
    image: ghcr.io/volschin/hibiscus-server:2.10
    depends_on:
      hibiscus-db:
        condition: service_healthy
        restart: true
    volumes:
      - hibiscus_cfg:/opt/hibiscus-server/cfg
      - jameica_data:/root/.jameica
      - ./hibiscus_password.txt:/run/secrets/hibiscus-pwd
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hibiscus.entrypoints=https"
      - "traefik.http.routers.hibiscus.rule=Host(`hibiscus.myfancydomain.finance`)"
      - "traefik.http.services.hibiscus.loadbalancer.server.port=8080"

  hibiscus-db:
    container_name: "hibiscus-db"
    image: mariadb:11
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    restart: unless-stopped
    volumes:
      - "hibiscus-db:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-mySecretRootPw}"
      - "MYSQL_DATABASE=hibiscus"
      - "MYSQL_USER=hibiscus"
      - "MYSQL_PASSWORD=hibiscus"
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.hibiscusdb.entrypoints=mariadb"
      - "traefik.tcp.routers.hibiscusdb.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.hibiscusdb.service=hibiscusdb"
      - "traefik.tcp.services.hibiscusdb.loadbalancer.server.port=3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

volumes:
  hibiscus-db:
  hibiscus_cfg:
  jameica_data:


networks:
  proxy:
    external: true
